services:
  database:
    build:
      context: ./MySQL
      dockerfile: Dockerfile
    container_name: db_1
    restart: always
    ports:
      - 4600:3306
    volumes:
      - ./MySQL/data:/var/lib/mysql
    networks:
      - eam_test
    healthcheck:
      test: ["CMD","mysql","-u","root","-proot_password_1234"]
      interval: 30s
      timeout: 10s
      retries: 5
  adminer:
    image: adminer
    container_name: db_test_1
    restart: always
    ports:
      - 8001:8080
    networks:
      - eam_test
    depends_on:
      database:
        condition: service_healthy

networks:
  eam_test:
    driver: bridge
    name: app_eam